### PR TITLE
Gradually stop at red light (fixes #13)

### LINKED ISSUE #13: Build a sophisticated version of Waypoint Updater
Make sure that the path planner (AKA waypoint updater) takes obstacles, traffic lights, and disruptions caused by the safety driver into account.

### PR DESCRIPTION
**Pull request by mithi**
- As suggested by @asimonov 10 < d < 30 works great! :+1: 
https://www.youtube.com/watch?v=iUpg4U_ERb0

### CODE REVIEW

**Comment by mithi** [comment]
# Update: Add gradual slowdown

Example:

```
MIN_DISTANCE = 22.5 #: Minimum distance from away from traffic light
MAX_DISTANCE = 45.0 #: Maximum distance from the traffic light to stop
DELTA_DISTANCE = 7.5 #: Buffer distance 
```

Car starts to slow down from `MAX_DISTANCE = 45 m` to traffic light until a complete stop at 30 m ```STOPPED_DISTANCE = MIN_DISTANCE + DELTA_DISTANCE``` 
Car should be within 22.5 m and 30 m of traffic light. If the car is less than 22.5 m near the traffic light it ignores the status of the traffic light as it's too late and its already in the intersection area.

**Comment by mithi** [comment]
Hi everyone, just for reference here’s a video of gradual stopping from this code https://www.youtube.com/watch?v=zx61O8XdkMg

**Comment by ljanyst** [comment]
Mithi, it worke very well. Thanks! :)

Can you please remove the warning messages?

**Comment by mithi** [comment]
Okay sure one sec! @ljanyst

**Comment by mithi** [comment]
Here’s the video for 40mph
https://www.youtube.com/watch?v=CM22iPj_HuE
But with the following parameters
```
LOOKAHEAD_WPS = 150 #: Number of waypoints we will publish
STALE_TIME = 2.0 #: Time since that indicates it is relatively new data
MIN_DISTANCE = 23.0 #: Minimum distance from away from traffic light
MAX_DISTANCE = 100.0 #: Maximum distance from the traffic light to stop
DELTA_DISTANCE = 7.0 #: Buffer distance which is where the car must be completely stopped
```

**Comment by mithi** [comment]
So I tested it on speeds = 45, 40, 30, 20, 10 
It seems to work quite well on my machine setup. 

Just tweak 
```
SLOW_DISTANCE = SPEED_MPH * 1.5 #: Distance amount where vehicle slows down
# NOTE: For SLOW_DISTANCE tweak coefficient as necessary
# > 1.5 for more gradual slowdown, < 1.5 for more abrupt stopping
```

Also depending on size of the road intersection you can tweak 
```
MIN_DISTANCE = 22.0 #: Minimum distance from away from traffic light
DELTA_DISTANCE = 8.0 #: Buffer distance to give time to completely stop
```

**Comment by ljanyst** [comment]
It works well for me too at 10 and 40 MPH. Thank you, Mithi!

**Review by ljanyst — APPROVED** [review]

**Comment by mithi** [comment]
@ljanyst WOOHOO! Finally! :)

**Pull request merged**
